import {test, expect} from '@playwright/test'

test('language search recolors map and keeps source-specific Chinese categories', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/lingua/')
  await expect(page.getByRole('heading',{name:'French Français'})).toBeVisible()
  const paths = page.locator('.leaflet-overlay-pane path.leaflet-interactive')
  await expect(paths).toHaveCount(241)
  const before = await paths.evaluateAll(nodes=>nodes.map(n=>n.getAttribute('fill')))
  await page.getByRole('button',{name:'English',exact:true}).click()
  const after = await paths.evaluateAll(nodes=>nodes.map(n=>n.getAttribute('fill')))
  expect(after).not.toEqual(before)
  await expect(page).toHaveURL(/lang=en/)
  await page.getByRole('button',{name:'Population %',exact:true}).click()
  expect(await paths.evaluateAll(nodes=>nodes.map(n=>n.getAttribute('fill')))).not.toEqual(after)
  await page.getByRole('button',{name:/Explore a language/}).click()
  await page.getByRole('combobox',{name:'Search languages'}).fill('Mandarin')
  await page.getByRole('combobox',{name:'Search languages'}).press('Enter')
  await expect(page.getByText(/not a Mandarin-only census/).first()).toBeVisible()
  await expect(page.getByRole('heading',{name:'Chinese 中文'})).toBeVisible()
  expect(errors).toEqual([])
})

test('country details include estimates, source note and explicit missing data', async ({page}) => {
  await page.goto('/lingua/')
  const search = page.getByRole('textbox',{name:'Find a country'})
  await search.fill('France')
  await page.locator('.country-list button').filter({hasText:'France'}).click()
  const detail = page.getByRole('region',{name:'COUNTRY SPOTLIGHT'})
  await expect(detail).toContainText('66,323,362')
  await expect(detail).toContainText('97%')
  await expect(detail).toContainText('Unicode CLDR 48.2')
  await page.getByRole('button',{name:'English',exact:true}).click()
  await expect(detail).toContainText('26,666,094')
  await page.getByRole('button',{name:/Explore a language/}).click()
  await page.getByRole('combobox',{name:'Search languages'}).fill('French')
  await page.getByRole('combobox',{name:'Search languages'}).press('Enter')
  await search.fill('China')
  await page.getByRole('button', {name:'· China No estimate',exact:true}).click()
  await expect(detail).toContainText('No estimate for French')
  await expect(detail).toContainText('Missing data does not mean')
})

test('map hover and click are interactive', async ({page}) => {
  await page.goto('/lingua/')
  const paths = page.locator('.leaflet-overlay-pane path.leaflet-interactive')
  await expect(paths).toHaveCount(241)
  const country = paths.nth(160)
  // Exercise Leaflet's DOM handlers independently of projection pixels.
  await country.dispatchEvent('mouseover')
  await expect(page.locator('.country-tooltip')).toBeVisible()
  await country.dispatchEvent('click')
  await expect(page.getByRole('region',{name:'COUNTRY SPOTLIGHT'})).toBeVisible()
  await expect(page.locator('.country-languages h4')).toHaveText('Languages spoken here')
  await page.getByRole('button',{name:'Zoom in',exact:true}).click()
  await page.getByRole('button',{name:'Reset map view',exact:true}).click()
})

test('mobile layout fits and selector supports keyboard escape and no results', async ({page}) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('/lingua/')
  await expect(page.getByRole('heading',{name:'French Français'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button',{name:/Explore a language/}).click()
  const input = page.getByRole('combobox',{name:'Search languages'})
  await input.fill('not-a-language')
  await expect(page.getByText('No matching languages. Try another name.')).toBeVisible()
  await input.fill('Spanish')
  await input.press('ArrowDown')
  await input.press('Enter')
  await expect(page.getByRole('heading',{name:'Spanish Español'})).toBeVisible()
  await page.getByRole('button',{name:/Explore a language/}).click()
  await input.press('Escape')
  await expect(input).not.toBeVisible()
  await expect(page.getByRole('button',{name:/Explore a language/})).toBeFocused()
  await page.screenshot({path:'test-results/mobile.png',fullPage:true})
})

test('production works offline after service worker precache, including reload and new language', async ({page,context}) => {
  await page.goto('/lingua/')
  await expect(page.getByText('Ready for offline exploration')).toBeVisible({timeout:20000})
  await page.evaluate(async()=>{await navigator.serviceWorker.ready})
  await page.reload()
  await expect(page.getByRole('heading',{name:'French Français'})).toBeVisible()
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading',{name:'French Français'})).toBeVisible()
  await expect(page.locator('.leaflet-overlay-pane path.leaflet-interactive')).toHaveCount(241)
  await page.getByRole('button',{name:'English',exact:true}).click()
  await expect(page.getByRole('heading',{name:'English English'})).toBeVisible()
  await page.screenshot({path:'test-results/desktop.png',fullPage:true})
  await context.setOffline(false)
})

test('failed initial data request gives retry that recovers', async ({page}) => {
  await page.route('**/data/languages.json',route=>route.abort())
  await page.goto('/lingua/')
  await expect(page.getByRole('alert')).toContainText('could not be loaded')
  await page.unroute('**/data/languages.json')
  await page.getByRole('button',{name:'Try again'}).click()
  await expect(page.getByRole('heading',{name:'French Français'})).toBeVisible()
})
